name: Deploy React Vite App to AWS S3 & CloudFront

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch
  pull_request:
    branches:
      - main  # Trigger deployment on PR merge to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Step 3: Create .env.production dynamically from secrets
      - name: Create .env.production file
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_KEY }}" >> .env.production
          echo "VITE_ANALYTICS_KEY=${{ secrets.VITE_Access_Key }}" >> .env.production
          cat .env.production  # Debugging: Print the contents of the .env.production file

      # Step 4: Install dependencies and build the app
      - name: Install dependencies and build app
        run: |
          npm install
          NODE_ENV=production npm run build  # Ensure it's in production mode

      # Step 5: Sync build folder to S3
      - name: Sync build folder to S3
        run: |
          aws s3 sync ./dist/ s3://$S3_BUCKET_NAME --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

      # Step 6: Invalidate CloudFront cache
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
